# Project: AddressBoosSYS
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Addressbook.o main.o
LINKOBJ  = Addressbook.o main.o
LIBS     = -L"E:/new-2023/Dev-Cpp/TDM-GCC-64/lib" -L"E:/new-2023/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -pg
INCS     = -I"E:/new-2023/Dev-Cpp/TDM-GCC-64/include" -I"E:/new-2023/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/new-2023/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"E:/new-2023/Dev-Cpp/TDM-GCC-64/include" -I"E:/new-2023/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/new-2023/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/new-2023/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = AddressBoosSYS.exe
CXXFLAGS = $(CXXINCS) -pg -fexec-charset=gbk
CFLAGS   = $(INCS) -pg -fexec-charset=gbk
DEL      = E:\new-2023\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Addressbook.o: Addressbook.cpp
	$(CPP) -c Addressbook.cpp -o Addressbook.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
